#pragma config(Motor,  motorA,          Left,          tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          Claw,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task main()
{
  bool fast = true;

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    getJoystickSettings(joystick);     // update buttons and joysticks

  	if (fast) {
  		motor[Left] = joystick.joy1_y1;
  		motor[Right] = joystick.joy1_y2;
  	}
  	else {
  		motor[Left] = joystick.joy1_y1/2;
  		motor[Right] = joystick.joy1_y2/2;
  	}

  	if(joy1Btn(5) == 1)
  		fast = false;
  	else if(joy1Btn(7) == 1)
  		fast = true;

  	if(joy1Btn(6) == 1)                  // If Joy1-Button1 is pressed:
      motor[Claw] = 200;              // Turn Motor A On at full power
    else                            // If Joy1-Button1 is NOT pressed:
     motor[Claw] = 0;                 // Turn Motor A Off

    if(joy1Btn(8) == 1)                  // If Joy1-Button1 is pressed:
      motor[Claw] = -200;              // Turn Motor A On at full power
    else                            // If Joy1-Button1 is NOT pressed:
     motor[Claw] = 0;                 // Turn Motor A Off
  }
}
